services:
  - type: web
    name: portfolio-digital-flask
    env: python
    plan: free
    buildPacks:
      - node:
          version: 20 # Versão atualizada para a mais recente LTS
      - python:
          version: 3.11
    rootDir: backend
    # Comando de build simplificado, sem o chmod
    buildCommand: "pip install -r requirements.txt && cd ../frontend && npm install --legacy-peer-deps && npm run build && cp -r dist/* ../backend/src/static/"
    startCommand: "gunicorn --chdir src main:app"